version: 0.2

env:
  variables:
    GO_VERSION: 1.16.4
phases:
  install:
    commands:
      - echo Installing...
      - go mod download
  pre_build:
    commands:
      - echo Start pre_build...
  build:
    commands:
      - echo Start build...
      - cd $CODEBUILD_SRC_DIR && go build
  post_build:
    commands:
      - echo Start post_build...
artifacts:
  files:
    - 'devops-cicd'