version: 0.2

env:
  variables:
    GO_VERSION: 1.16.4
  secrets-manager:
    DOCKERHUB_USERNAME: "dockerhub/credentials:username"
    DOCKERHUB_PASS: "dockerhub/credentials:password"
phases:
  install:
    commands:
      - docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASS
      - go mod download
  pre_build:
    commands:
      - echo Start pre_build...
  build:
    commands:
      - echo Start build...
      - cd $CODEBUILD_SRC_DIR && go build
  post_build:
    commands:
      - echo Start post_build...
artifacts:
  files:
    - 'devops-cicd'